### ISSUE TITLE
Populate GitHub repo URL with Chrome Web Store URL

### ISSUE THREAD

**Issue by hkdobrev** [ismamz/refined-wikipedia#1]
Could you add the [Chrome extension URL in the Web Store](https://chrome.google.com/webstore/detail/refined-wikipedia/cnmnmlclbofploblcanilidpmklleppe) to the URL field of the GitHub repo next to description?

It will help people who landed on the GitHub repo first and want to quickly install it and try it out.

**Comment by ismamz** [comment]
Yes, sure!. Should I add the [URL in the Web Store for Refined Twitter](https://chrome.google.com/webstore/detail/refined-twitter/nlfgmdembofgodcemomfeimamihoknip) too? To be consistent?

**Comment by hkdobrev** [comment]
@ismamz I meant the URL at the top of the GitHub repo:

![screen shot 2016-08-24 at 21 22 26](https://cloud.githubusercontent.com/assets/506129/17942638/e7854c36-6a40-11e6-987d-51c72ab2cd0a.png)

**Comment by ismamz** [comment]
Ah, ok! :smile:
It's done!
