### ISSUE TITLE
Disambiguation in dark mode is not readable

### ISSUE THREAD

**Issue by tanmayrajani** [ismamz/refined-wikipedia#4]
As seen in the screenshot below, disambiguation in the dark mode isn't quite readable.

![disambiguation](https://user-images.githubusercontent.com/8295888/31305328-d4ae1fd8-ab54-11e7-8560-05a5b7fc5463.png)

**Comment by ismamz** [comment]
Hi @tanmayrajani, I've submit a new version (0.1.2) fixing this issue. Thanks for the feedback!

**Comment by tanmayrajani** [comment]
That was quick! Thank you for this great extension! Cheers :clinking_glasses:
